/**
 * 首页演示数据 —— 仅用于开发/Storybook/测试，**不要**在生产页面中导入。
 * 生产页面在后端不可用时显示 EmptyState，而非回退到此数据。
 */
export const MOCK_POSTS = [
  {
    id: '1',
    title: 'Next.js 14 App Router 完全指南',
    content: '',
    summary: '深入探讨 Next.js 14 中 App Router 的核心概念、文件约定、路由机制以及最佳实践。',
    coverImage: '',
    authorId: 'mock-1',
    author: { id: 'mock-1', username: '技术小王', displayName: '技术小王', avatar: '' },
    tags: ['Next.js', 'React', '前端'],
    status: 'published' as const,
    likeCount: 128,
    commentCount: 32,
    isLiked: false,
    isFavorited: false,
    createdAt: '2026-03-25T10:30:00Z',
    updatedAt: '2026-03-25T10:30:00Z',
  },
  {
    id: '2',
    title: 'React Server Components 深度解析',
    content: '',
    summary: 'Server Components 是 React 的革命性特性，本文将带你从原理到实践全面掌握。',
    coverImage: '',
    authorId: 'mock-2',
    author: { id: 'mock-2', username: '前端达人', displayName: '前端达人', avatar: '' },
    tags: ['React', 'Server Components', '性能优化'],
    status: 'published' as const,
    likeCount: 256,
    commentCount: 67,
    isLiked: false,
    isFavorited: false,
    createdAt: '2026-03-24T08:15:00Z',
    updatedAt: '2026-03-24T08:15:00Z',
  },
  {
    id: '3',
    title: 'TypeScript 5.0 新特性一览',
    content: '',
    summary: 'TypeScript 5.0 带来了装饰器、const 类型参数、inferred 类型等重磅新特性。',
    coverImage: '',
    authorId: 'mock-3',
    author: { id: 'mock-3', username: 'TS布道者', displayName: 'TS布道者', avatar: '' },
    tags: ['TypeScript', 'JavaScript', '编程语言'],
    status: 'published' as const,
    likeCount: 89,
    commentCount: 21,
    isLiked: false,
    isFavorited: false,
    createdAt: '2026-03-23T14:20:00Z',
    updatedAt: '2026-03-23T14:20:00Z',
  },
  {
    id: '4',
    title: 'Tailwind CSS v4 实战技巧',
    content: '',
    summary: 'Tailwind CSS v4 引入了全新的引擎和诸多改进，让你的样式开发效率翻倍。',
    coverImage: '',
    authorId: 'mock-4',
    author: { id: 'mock-4', username: 'CSS魔法师', displayName: 'CSS魔法师', avatar: '' },
    tags: ['TailwindCSS', 'CSS', 'UI'],
    status: 'published' as const,
    likeCount: 312,
    commentCount: 45,
    isLiked: false,
    isFavorited: false,
    createdAt: '2026-03-22T16:40:00Z',
    updatedAt: '2026-03-22T16:40:00Z',
  },
  {
    id: '5',
    title: '构建高可用微服务架构实践',
    content: '',
    summary: '从服务拆分、API网关、服务发现到链路追踪，全面介绍微服务架构落地的最佳实践。',
    coverImage: '',
    authorId: 'mock-5',
    author: { id: 'mock-5', username: '架构师老李', displayName: '架构师老李', avatar: '' },
    tags: ['微服务', '架构', 'Go'],
    status: 'published' as const,
    likeCount: 178,
    commentCount: 53,
    isLiked: false,
    isFavorited: false,
    createdAt: '2026-03-21T09:00:00Z',
    updatedAt: '2026-03-21T09:00:00Z',
  },
  {
    id: '6',
    title: 'Docker Compose 开发环境最佳配置',
    content: '',
    summary: '使用 Docker Compose 一键搭建包含数据库、缓存、消息队列的完整开发环境。',
    coverImage: '',
    authorId: 'mock-6',
    author: { id: 'mock-6', username: 'DevOps小王', displayName: 'DevOps小王', avatar: '' },
    tags: ['Docker', 'DevOps', '开发工具'],
    status: 'published' as const,
    likeCount: 95,
    commentCount: 18,
    isLiked: false,
    isFavorited: false,
    createdAt: '2026-03-20T11:30:00Z',
    updatedAt: '2026-03-20T11:30:00Z',
  },
];

export const TRENDING_MOCK = [
  { id: '7', title: '2026年前端技术趋势预测', likeCount: 456 },
  { id: '8', title: '从零到一搭建 CI/CD 流水线', likeCount: 342 },
  { id: '9', title: 'React vs Vue vs Svelte 对比评测', likeCount: 289 },
];
